// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EStoreFrontEnd.Models.EfModels;

public partial class Member
{
    public int Id { get; set; }

    public string Account { get; set; }

    public string HashedPassword { get; set; }

    public string Email { get; set; }

    public string Name { get; set; }

    public string Mobile { get; set; }

    public bool? IsConfirmed { get; set; }

    public string NewMemberConfirmCode { get; set; }

    public string ResetPasswordConfirmCode { get; set; }

    public virtual ICollection<Cart> Carts { get; set; } = new List<Cart>();

    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();
}