// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApplication4.Models.EfModels;

public partial class SupplierContact
{
    public int Id { get; set; }

    public int SupplierId { get; set; }

    public string ContactName { get; set; }

    public string Email { get; set; }

    public string Tel { get; set; }

    public bool IsPrimary { get; set; }
}